### ISSUE TITLE
Readme looks a bit wonky on mobile

### ISSUE THREAD

**Issue by rvanasa** [dfinity/portal#1079]
The readme looks great on desktop screen sizes, but this is what I saw when opening the repository from my phone:

<img src="https://user-images.githubusercontent.com/522097/219489186-2b896bfb-d1e5-4137-810a-1a4bdc109f6f.png" width="500"/>

Opening this issue with the hope that there's a solution which allows us to keep the nice-looking desktop readme layout.

**Comment by jessiemongeon1** [comment]
Addressing this in https://github.com/dfinity/portal/pull/2633
