### ISSUE TITLE
markup appearing in the "Installing the SDK" page

### ISSUE THREAD

**Issue by daniel-wong-dfinity-org** [dfinity/portal#1143]
Here are a couple of screenshots of what I'm seeing. I would try to come up with a fix for this myself, but my markdown skills are not strong enough. It seems to get confused by indented triple backtick.

![Screen Shot 2023-02-27 at 8 22 51 PM](https://user-images.githubusercontent.com/97631336/221753405-8283f14c-3e5b-48a8-a053-ed49d628d1d2.png)
![Screen Shot 2023-02-27 at 8 22 38 PM](https://user-images.githubusercontent.com/97631336/221753420-6826bde2-de9a-401c-bf71-61e7fdd6e89c.png)

**Comment by jessiemongeon1** [comment]
This page's format has been fixed: https://internetcomputer.org/docs/current/developer-docs/getting-started/install/#installing-dfx
