### ISSUE TITLE
Outdated docs page

### ISSUE THREAD

**Issue by Sheikh-JamirAlam** [dfinity/portal#1156]
The "Getting Started with Free Cycles" page is outdated.

These are the steps that are being shown in the docs:
![image](https://user-images.githubusercontent.com/48979376/222335729-d4f0e571-4720-4500-ba5e-63e667ee419c.png)

Now it has changed to:
![image](https://user-images.githubusercontent.com/48979376/222335974-cb10a13f-720b-4481-8827-bf8e700fc384.png)

I can work on it and update the page.

**Comment by sesi200** [comment]
Hi @Sheikh-JamirAlam if you're willing to update the guide that would be awesome! I'd be very happy to merge a PR if you get around to making one.

Note to self: tracking as [SDK-1016](https://dfinity.atlassian.net/browse/SDK-1016)

**Comment by Sheikh-JamirAlam** [comment]
@sesi200 Alright, I would love to work on it.

**Comment by sesi200** [comment]
If you need help, let me know

**Comment by Sheikh-JamirAlam** [comment]
@sesi200 Can you review my pr?

**Comment by sesi200** [comment]
Apologies for the delay, I was out sick. Will get to reviewing today
