### ISSUE TITLE
I can't clone this repo

### ISSUE THREAD

**Issue by e274426380** [dfinity/portal#1454]
![image](https://github.com/dfinity/portal/assets/75345973/453aac90-537e-490d-a595-562b56e9c899)
i fork this repo,and clone has been failed

**Comment by sesi200** [comment]
Are you on a file system that doesn't support certain characters in the file path? Maybe if you download the repo as a zip you have more success?

**Comment by khejit** [comment]
Had this problem on Windows. Cloned  without problem from WSL.
