### ISSUE TITLE
dead links in Reference Documentation: IC Interface Specification

### ISSUE THREAD

**Issue by smallstepman** [dfinity/portal#149]
https://smartcontracts.org/docs/current/references/ic-interface-spec#system-api
https://github.com/dfinity/portal/blob/master/docs/references/ic-interface-spec.md

all `[...](#system-api)` links (total of 6) in markdown point to nowhere. I'm unsure if they should point to 
- https://smartcontracts.org/docs/current/references/ic-interface-spec#canister-interface-system-api, or,
- https://smartcontracts.org/docs/current/references/ic-interface-spec#abstract-canisters-to-system-api

**Comment by Acetarax** [comment]
> https://smartcontracts.org/docs/current/references/ic-interface-spec#system-api https://github.com/dfinity/portal/blob/master/docs/references/ic-interface-spec.md
> 
> all `[...](#system-api)` links (total of 6) in markdown point to nowhere. I'm unsure if they should point to
> 
> * https://smartcontracts.org/docs/current/references/ic-interface-spec#canister-interface-system-api, or,
> * https://smartcontracts.org/docs/current/references/ic-interface-spec#abstract-canisters-to-system-api

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by smallstepman** [comment]
works https://internetcomputer.org/docs/current/references/ic-interface-spec/#system-api
