### ISSUE TITLE
Invalid quick start links for dfx 0.9.3

### ISSUE THREAD

**Issue by sandeepV2** [dfinity/portal#1577]
Environment:
 node - v16.19.0
 dfx - 0.9.3

Command used to install dfx:
`DFX_VERSION=0.9.3 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"`

After creating new project I get the following links to get started.
`$ dfx new hello

To learn more before you start coding, see the documentation available online:

- Quick Start: https://sdk.dfinity.org/docs/quickstart/quickstart-intro.html
- SDK Developer Tools: https://sdk.dfinity.org/docs/developers-guide/sdk-guide.html
- Motoko Language Guide: https://sdk.dfinity.org/docs/language-guide/motoko.html
- Motoko Quick Reference: https://sdk.dfinity.org/docs/language-guide/language-manual.html`

None of the mentioned links are working and end up in page not found error.  

![Screenshot 2023-06-14 at 5 38 09 PM](https://github.com/dfinity/portal/assets/52043035/34c2bd67-6b93-4df2-9b6a-42eacb0601ca)

Am i missing something here ? or May be we should update the doc links.

**Comment by sesi200** [comment]
dfx 0.9.3 is _extremely_ outdated (released 15 months ago). Please use a version that is (somewhat) current

**Comment by sandeepV2** [comment]
Thank you @sesi200 , The tutorial i am following must be pretty old.
