### ISSUE TITLE
Incorrect information about nodejs in ic-cdk install documentation

### ISSUE THREAD

**Issue by testpuddle** [dfinity/portal#1773]
In https://github.com/dfinity/portal/edit/master/docs/developer-docs/setup/install/index.mdx

line 112 states node 16 or greater is required.
dfx will complain and throw an error if Node version 19 or 20.05.5 

Line 112 should be corrected until the code tested with 20.0.5 and state up to version 18.
![2023-08-08](https://github.com/dfinity/portal/assets/29495946/74aff49c-8a9c-4eb0-beee-c53b01d0c336)

**Comment by jessiemongeon1** [comment]
This issue is being resolved in: https://github.com/dfinity/portal/pull/2633
