### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by jeevan42** [dfinity/portal#1932]
I clone the project successfully, i use WSL and when give command for deploy it gives me error and also giving so much errors while installing the package, i also tried to install the packages one by one, still it gives error like file path and another errors, please suggest me effective way to start the projects.

**Comment by jessiemongeon1** [comment]
Hey @jeevan42 , are you trying to clone the portal repo to make a contribution, or are you trying to clone a sample project showcased in the docs?
