### ISSUE TITLE
broken links "Basic Dependency" example

### ISSUE THREAD

**Issue by bws9000** [dfinity/portal#201]
https://internetcomputer.org/docs/current/developer-docs/build/languages/rust/multiply-dependency

# Implement Motoko canister
- 4. Copy and paste [this code](https://internetcomputer.org/assets/files/mul-deps-31d6cfe0d16ae931b73c59d7e0c089c0.mo) into the main.mo file. ( blank file download )

# Replace the default Rust canister
- 3. Copy and paste [this code](https://internetcomputer.org/assets/files/mul-deps-main-31d6cfe0d16ae931b73c59d7e0c089c0.rs) into the lib.rs file. ( blank page )

You can't continue with the example with these broken links.

**Comment by sesi200** [comment]
Thanks for the report! Will be fixed in #203
