### ISSUE TITLE
Won't authenticate to twitter even my account created past 90 days.

### ISSUE THREAD

**Issue by jomarmontuya** [dfinity/portal#207]
I'm having issues authenticating to twitter even my account is past 90 days. I'm following a tutorial and would like to try deploying my app to IC networks but having trouble because I don't have cycles. 

Hoping that they should also add the github authorization cause not all devs have twitter just saying.

**Comment by sesi200** [comment]
This is not a documentation issue. Please ask on forum.dfinity.org
