### ISSUE TITLE
Ledger Wasm too big ... again!

### ISSUE THREAD

**Issue by blutooth** [dfinity/portal#212]
Why does this page (https://internetcomputer.org/docs/current/developer-docs/functionality/ledger/ledger-local-setup) yet again point to a ledger canister that is too big and not deployable? This is still a year after launch and yet the public docs do not have a ledger canister that is deployable locally...despite 3 interventions from this forum thread... This is getting embarrassing now. 

Please put in an automated check to ensure the size of the ledger is under 2mb  before tagging. 

https://forum.dfinity.org/t/ledger-wasm-too-big/11274/6

**Comment by roman-kashitsyn** [comment]
Created https://github.com/dfinity/portal/pull/215 to address the issue.

> Please put in an automated check to ensure the size of the ledger is under 2mb before tagging.

We have a CI check that verifies that, but the doc was written before this became a concern. 

We also have https://github.com/dfinity/sdk/issues/1982 to address the issue more systematically (forcing people to follow 10-step setup process in inhumane).
