### ISSUE TITLE
Consider adding .nvm and/or an "engines" entry in the package.json

### ISSUE THREAD

**Issue by meodai** [dfinity/portal#2183]
While wanting to work on the site i encountered issues when using `npm ci` turned out my node version is too modern. We should specify it in a `.nvm` file or as and `engines` entry in the packages.json 

I had to randomly try node version I had installed locally until I found one that works.

node **v16.14.2** works fine.

**Comment by meodai** [comment]
PS; the readme mentions using `npm install`. I would suggest changing this to `npm ci`

**Comment by peterpeterparker** [comment]
I reported a similar issue in April 2023, I guess we can still wait few more years...

https://github.com/dfinity/portal/issues/1283

**Comment by peterpeterparker** [comment]
`npm ci` with Node v18.6 worked out indeed.

**Comment by jessiemongeon1** [comment]
This issue is being resolved in: https://github.com/dfinity/portal/pull/2633
