### ISSUE TITLE
The unnecessary use of sudo for step 8 of the cycles-faucet.md

### ISSUE THREAD

**Issue by testpuddle** [dfinity/portal#2253]
https://github.com/dfinity/portal/edit/master/docs/developer-docs/setup/cycles/cycles-faucet.md

Step 8 suggests that upgrade be done by using sudo dfx upgrade.
dfx is traditionally installed with user level privileges and does not require suid = 0 root powers.
In the past, installing dfx with sudo caused issues with reading and writing key stores as ownership was set to root.

I wonder if the correct recommendation would be:  dfx upgrade vs sudo dfx upgrade.

**Comment by jessiemongeon1** [comment]
This issue is being resolved in: https://github.com/dfinity/portal/pull/2633
