### ISSUE TITLE
Receiving cycles for faucet should be more accessible, or the conditions should be made more clear in the documentation

### ISSUE THREAD

**Issue by omnivirens** [dfinity/portal#2334]
I am following the Developer Journey to get accustomed with the ecosystem. For this I made a new github account separate from my professional github account. Now the community manager (TedR on discord) tells me that I need to have code in my github before I can receive cycles from the faucet. Since there is no testnet, this should really be made more clear in the documentation. I don't mind funding it myself but being gated this way is really off putting and doesn't really inspire people to join the ecosystem.

**Comment by omnivirens** [comment]
I am a machine learning engineer by profession. I would prefer to keep my professional account separated from my hobby account. I would just suggest making this more clear in the documentation. It isn't stated anywhere in the documentation that you would be gate-kept by your github not having any code in it. You even mention this in the documentation page: 

> This coupon is good for new developers since it doesn't require that you transfer ICP tokens into cycles, and doesn't require a purchase of tokens to get started.

If I knew having code in your github was a required condition I wouldn't even have bothered to put any effort in obtaining the coupon and just funded it myself. It seems like ICP is trying hard to get more developers joining the ecosystem, this process has the exact opposite effect in my opinion.

**Comment by domwoe** [comment]
I agree with you. We have to always tweak the process a bit but we'll soon update the documentation. 
It's unfortunately quite hard to distinguish an honest dev with a fresh Github profile from someone who tries to abuse the system by creating fresh accounts repeatedly.
