### ISSUE TITLE
icrc2_allowance example is incorrect

### ISSUE THREAD

**Issue by testpuddle** [dfinity/portal#2554]
In https://internetcomputer.org/docs/current/developer-docs/integrations/icrc-1/interact-with-ICRC-1-ledger#icrc-2-endpoints

Example with method icrc2_allowance instead of icrc2_transfer_from

Wrong example:
dfx canister call icrc1_ledger_canister icrc2_transfer_from "(record { account = record{owner = principal \"${DEFAULT}\";}; spender = record{owner = principal \"sckqo-e2vyl-4rqqu-5g4wf-pqskh-iynjm-46ixm-awluw-ucnqa-4sl6j-mqe\";} })"  

Correct example:
dfx canister call icrc1_ledger_canister icrc2_allowance "(record { account = record{owner = principal \"${DEFAULT}\";}; spender = record{owner = principal \"sckqo-e2vyl-4rqqu-5g4wf-pqskh-iynjm-46ixm-awluw-ucnqa-4sl6j-mqe\";} })"

**Comment by jessiemongeon1** [comment]
This issue is being resolved in: https://github.com/dfinity/portal/pull/2633
