### ISSUE TITLE
I can't Optimize the code within the target?

### ISSUE THREAD

**Issue by aliscie** [dfinity/portal#258]
when I ran `ic-cdk-optimizer target/wasm32-unknown-unknown/release/_rust_canister_.wasm -o target/wasm32-unknown-unknown/release/_rust_canister_-opt.wasm` I got the following error.
```error
thread 'main' panicked at 'Could not read the file.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/ic-cdk-optimizer-0.3.4/src/main.rs:34:27
```

**Comment by sesi200** [comment]
Correct place to discuss this is here: https://github.com/dfinity/cdk-rs/issues/278
