### ISSUE TITLE
Invalid link in the README

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/portal#2612]
In the README the link `https://app.netlify.com/sites/icportal/deploys` is invalid.

<img width="1536" alt="Capture d’écran 2024-03-07 à 07 35 45" src="https://github.com/dfinity/portal/assets/16886711/4c4c5683-fd83-41e2-94c9-9bf5cd32cfdd">
<img width="1536" alt="Capture d’écran 2024-03-07 à 07 35 55" src="https://github.com/dfinity/portal/assets/16886711/07b24ce0-843d-4670-8767-d098f58992da">

**Comment by jessiemongeon1** [comment]
Thanks David, I've removed this link from the README.
