### ISSUE TITLE
GitHub Markdown Alerts are not rendered correctly

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#2689]
We should use a plugin similar to [this](https://github.com/incentro-dc/remark-github-admonitions-to-directives?tab=readme-ov-file) to enable a consistent markdown rendering across docusaurus and GitHub. I tried the aforementioned plugin but didn't want to waste too much time due to issues importing it correctly.

**Comment by jessiemongeon1** [comment]
@dfx-json and I have discussed this and are working on a plan to resolve.

**Comment by letmejustputthishere** [comment]
> @dfx-json and I have discussed this and are working on a plan to resolve.

amazing, thank you 🎉

**Comment by jessiemongeon1** [comment]
Update: This plugin is currently not supported for our version of Docusaurus, so for now we've updated the Examples repo to use the Markdown format instead of the Github format.
