### ISSUE TITLE
The cycles faucet does not work

### ISSUE THREAD

**Issue by apecollector** [dfinity/portal#269]
I'm developing an app and had a bad experience with the docs referencing the cycles faucet.  If it's not working or has potential to be out of cycles that should be made clear in the docs, otherwise it just leaves a really poor first impression.

I followed the steps, linked to twitter, and it said it was out of cycles:

<img width="653" alt="Screen Shot 2022-06-26 at 12 31 04 PM" src="https://user-images.githubusercontent.com/100589991/176083638-e76e8f31-2dad-43af-8da3-3f9de3bd60cd.png">

**Comment by Acetarax** [comment]
> I'm developing an app and had a bad experience with the docs referencing the cycles faucet. If it's not working or has potential to be out of cycles that should be made clear in the docs, otherwise it just leaves a really poor first impression.
> 
> I followed the steps, linked to twitter, and it said it was out of cycles:
> 
> <img alt="Screen Shot 2022-06-26 at 12 31 04 PM" width="653" src="https://user-images.githubusercontent.com/100589991/176083638-e76e8f31-2dad-43af-8da3-3f9de3bd60cd.png">

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by sesi200** [comment]
The Twitter flow on the faucet has been disabled because of too frequent abuse. Please go to the DFINITY Discord to the #cycles-faucet channel and ask for a code there.

**Comment by apecollector** [comment]
> The Twitter flow on the faucet has been disabled because of too frequent abuse. Please go to the DFINITY Discord to the #cycles-faucet channel and ask for a code there.

Shouldn't the website be updated to reflect this fact, otherwise all my points of a bad initial impression are still valid.

https://internetcomputer.org/docs/current/developer-docs/quickstart/cycles-faucet/

**Comment by sesi200** [comment]
Fair point. The work to update the page is tracked internally and won't get lost, but we have a lot of people on vacation right now so I'm closing this so we have some less duplication.

Apologies for not really addressing your report in my response, I replied mostly to the title. Since the faucet works again I considered it handled.
