### ISSUE TITLE
Delete section Avoid traps after await

### ISSUE THREAD

**Issue by andrew-lee-work** [dfinity/portal#2727]
Delete the section `### Avoid traps after await` entirely, as per @robin-kunzler's suggestion.

> I would like to remove it in a separate PR. It would make it easier to reinstate the section in case we want to do that later.

_Originally posted by @andrew-lee-work in https://github.com/dfinity/portal/pull/2356#discussion_r1547083249_

**Comment by jessiemongeon1** [comment]
Addressed in https://github.com/dfinity/portal/pull/2851
