### ISSUE TITLE
Add documentation about what trusting a canister entails

### ISSUE THREAD

**Issue by andrew-lee-work** [dfinity/portal#2818]
> I think trusting a canister implies trusting its subnet and various other dependencies. I'm not aware if we have documentation about what trusting a canister entails, but if not it would be useful to create it and link to it from here.

_Originally posted by @andrew-lee-work in https://github.com/dfinity/portal/pull/2356#discussion_r1552123315_

**Comment by jessiemongeon1** [comment]
We have a page on trust in canisters: https://internetcomputer.org/docs/current/concepts/trust-in-canisters/
