### ISSUE TITLE
syntaxis error

### ISSUE THREAD

**Issue by vv-work** [dfinity/portal#284]
At the end of [the page](https://internetcomputer.org/docs/current/developer-docs/build/languages/motoko/basic-concepts) with basic syntaxis there is type  `jimport` instead of `import`

Here is the full code:
```motoko
jimport Debug "mo:base/Debug";

assert 1 > 0; // never traps
Debug.print "bingo!";
```

**Comment by ggreif** [comment]
I see
<img width="284" alt="Screenshot 2022-07-04 at 18 34 03" src="https://user-images.githubusercontent.com/1312006/177193047-dcbc2887-a312-4901-91c4-aacec1c22f64.png">

**Comment by vv-work** [comment]
Yes.
