### ISSUE TITLE
Documentation Issue: ICRC-1 Ledger Setup - Steps dont make sense

### ISSUE THREAD

**Issue by selcukbeyhan** [dfinity/portal#2902]
Hi,
in the icrc-1 ledger-setup documentation:
https://internetcomputer.org/docs/current/developer-docs/defi/icrc-1/icrc1-ledger-setup
there are some items which could be improved:

step-2:
which language and settings should the new project be created?

step-3:
It talks about downloading some files but it doesnt talk anything about where to place/put these files and what to do with them.

thanks

**Comment by jessiemongeon1** [comment]
Addressed in https://github.com/dfinity/portal/pull/2922
