### ISSUE TITLE
ICRC-1 Token Deployment fails without proper hint - bad magic number

### ISSUE THREAD

**Issue by selcukbeyhan** [dfinity/portal#2903]
Hi,

for this code:
export MINTER=$(dfx identity get-principal)
export TOKEN_NAME="My Token"
export TOKEN_SYMBOL="MYTO"
export PRE_MINTED_TOKENS=10_000_000_000
export TRANSFER_FEE=10_000
export DEFAULT=$(dfx identity get-principal)
export ARCHIVE_CONTROLLER=$(dfx identity get-principal)
export TRIGGER_THRESHOLD=2000
export NUM_OF_BLOCK_TO_ARCHIVE=1000
export CYCLE_FOR_ARCHIVE_CREATION=10000000000000
export FEATURE_FLAGS=false

dfx deploy doto_ledger_canister --verbose --playground --argument "(variant {Init =
record {
     token_symbol = \"${TOKEN_SYMBOL}\";
     token_name = \"${TOKEN_NAME}\";
     minting_account = record { owner = principal \"${MINTER}\" };
     transfer_fee = ${TRANSFER_FEE};
     metadata = vec {};
     feature_flags = opt record{icrc2 = ${FEATURE_FLAGS}};
     initial_balances = vec { record { record { owner = principal \"${DEFAULT}\"; }; ${PRE_MINTED_TOKENS}; }; };
     archive_options = record {
         num_blocks_to_archive = ${NUM_OF_BLOCK_TO_ARCHIVE};
         trigger_threshold = ${TRIGGER_THRESHOLD};
         controller_id = principal \"${ARCHIVE_CONTROLLER}\";
         cycles_for_archive_creation = opt ${CYCLE_FOR_ARCHIVE_CREATION};
     };
 }
})"

I get following error:
developer@debian:~/Work/BloodBank/icp-token/v2.0/doto_ledger_canister$ ./token-creation-script.sh 
WARN: The default identity is not stored securely. Do not use it to control a lot of cycles/ICP. Create a new identity with `dfx identity new` and use it in mainnet-facing commands with the `--identity` flag
Deploying: doto_ledger_canister
All canisters have already been created.
Building canisters...
Installing canisters...
Previously installed module hash: None
Installing code for canister doto_ledger_canister, with canister ID oqjvn-fqaaa-aaaab-qab5q-cai
New wasm module hash: 9ab4baff988fb961d5fc216a887514d55f98bc959b5931325a63087ee882d66f
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
  Failed while trying to install all canisters.
    Failed to install wasm module to canister 'doto_ledger_canister'.
      install failed
        The replica returned a rejection error: reject code CanisterReject, reject message IC0503: Error from Canister ozk6r-tyaaa-aaaab-qab4a-cai: Canister trapped explicitly: Panicked at 'called `Result::unwrap()` on an `Err` value: WasmParse("Bad magic number (at offset 0)")', lib.rs:33:49, error code None
developer@debian:~/Work/BloodBank/icp-token/v2.0/doto_ledger_canister$ 

any idea what is wrong here?

**Comment by jessiemongeon1** [comment]
Hey @selcukbeyhan , this error is because you are deploying to the playground, which doesn't accept gzipped Wasm files: https://forum.dfinity.org/t/error-deploying-canister-on-playground/23030/10

I've added a note in the tutorial to indicate this. Thanks!
