### ISSUE TITLE
Minor spelling

### ISSUE THREAD

**Issue by testpuddle** [dfinity/portal#3096]
Line 14:  An **issuer** is a service or app that can issue a verifiable credential (VC) to a user. On ICP, an issuer is an exposed API that recieves calls   --- should be receives.

Also recieves is used in https://internetcomputer.org/docs/current/developer-docs/identity/verifiable-credentials/issuer
Should be corrected to receives.

**Comment by jessiemongeon1** [comment]
PR to fix: https://github.com/dfinity/portal/pull/3097
