### ISSUE TITLE
Realistic Computation and Storage Costs

### ISSUE THREAD

**Issue by neokree** [dfinity/portal#349]
Hello, 

I was trying to identify how much my dApp would cost (in terms of ICP/month) based on estimated monthly active users. 
I found https://internetcomputer.org/docs/current/developer-docs/deploy/computation-and-storage-costs/ but to me it's not very clear to me how should I translate: 
1. ICP to cycles
2. blockchain interaction to type of transaction

For example, if I have a very simple canister that:
1. Read a number (query)
2. Set the number (update)

What type of transaction costs would be used to burn the cycles? 
Some, like "Compute Percent Allocated Per Second", are not clear to me since I don't know how much the compute power of a replica is, so I don't know how much can it be estimated

Having an official calculator, or better, a program that estimates, for a specific canister, how much it requires in ICP per call, would be really helpful to understand the costs required.

**Comment by sesi200** [comment]
https://forum.dfinity.org/t/calculate-an-estimate-of-cycles-consumption-a-universal-example/12526/17 This post's author wanted to turn it into a proper blog post that shows how to calculate that. I should follow up with them how it's going.

**Comment by jessiemongeon1** [comment]
The Gas Cost page has since been overhauled and updated: https://internetcomputer.org/docs/current/developer-docs/gas-cost

There is also a 'cost estimations' page: https://internetcomputer.org/docs/current/developer-docs/cost-estimations-and-examples
