### ISSUE TITLE
add description for hotkey

### ISSUE THREAD

**Issue by bytesun** [dfinity/portal#3635]
more detail info about hotkey, what is hotkey? what it can do? 
some dapps ask hotkey setting, most users don't know what it is, especially any risk to lose fund. 
found helpful info at https://forum.dfinity.org/t/help-me-understand-a-little-more-about-hotkeys/9817 , it's better to make it clear at official document.

**Comment by jessiemongeon1** [comment]
Thanks @bytesun , I've opened a PR to add some additional clarifying details: https://github.com/dfinity/portal/pull/3639
