### ISSUE TITLE
fix: clarify conditions under which canister stable memory is cleared

### ISSUE THREAD

**Issue by eliezhao** [dfinity/portal#3821]
Regarding the issue of when stable memory might lose canister data, I initially submitted a PR but noticed the CLA hasn’t been approved, so I decided to open an issue instead:

[Here](https://github.com/dfinity/portal/blob/master/docs/developer-docs/smart-contracts/maintain/storage.mdx#stable-memory) 

> When a canister is reinstalled or upgraded, the data stored in stable memory is not cleared or removed.

stable memory should persist as long as the canister’s cycles are not depleted or the canister is not reinstalled.

Suggested modification:

> Unless a canister is reinstalled or its data is cleared due to cycle depletion, the data stored in stable memory is not cleared or removed.

**Comment by jessiemongeon1** [comment]
Thanks, here is the PR for this change: https://github.com/dfinity/portal/pull/3824
