### ISSUE TITLE
Missing auth_client_demo in the github repository

### ISSUE THREAD

**Issue by testpuddle** [dfinity/portal#3822]
I am pretty disappointed to again not be able to advance in developing an app on the ICP by followng the documentation.

I want to create a dapp that 1. Logs in.  

The auth_client_demo has been removed from the  github repository.

Maybe a dependency could be executed to ensure this does not happen?

It must be disheartening for Jessie to put all the effort into making the developers journey/ladder and then things break.

**Comment by jessiemongeon1** [comment]
Hey @testpuddle , this example got moved to an archive folder in the repo: https://github.com/dfinity/examples/tree/master/archive/motoko/auth_client_demo

There's probably a few links that need to be updated. I'll take a look, thanks!
