### ISSUE TITLE
 "ICP transfers"  link broken

### ISSUE THREAD

**Issue by bytesun** [dfinity/portal#3891]
https://internetcomputer.org/docs/current/developer-docs/defi/tokens/token-standards#icp-tokens

**Comment by kriddreak** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action to keep your wallet safe.

Please write to us using the “Chat Support” icon located on the [Dfinity Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!
