### ISSUE TITLE
Addition of code snippets in the articles. 

### ISSUE THREAD

**Issue by BappaBanerjee** [dfinity/portal#404]
Hi, I think it will be very good if you add some code snippets to the description of the function or the variables. It will gives a clear view of the things.

**Comment by sesi200** [comment]
Hi @BappaBanerjee, can you please clarify a bit where exactly you're talking about? Maybe if you could add a link to one example that would be great

**Comment by jessiemongeon1** [comment]
The dev docs have recently gone through a major update & overhaul, including adding code snippets across several pages. 

Please let us know if you'd like to reopen this issue and point to a specific page where a code snippet would be beneficial to add. 

Thank you!
