### ISSUE TITLE
Can you add a repo link for each of the Motoko-Base references?

### ISSUE THREAD

**Issue by lightninglad91** [dfinity/portal#431]
I've been using the Motoko Reference guide on a daily basis. I like to understand what's going on under the hood, so I typically flip back and forth between the reference portal and the source code.  

Would it be possible to include a link to the source code for each of the base types?  That way I can go straight to the source code from the reference guide.

If not I can stick to using bookmarks. Thanks :)

**Comment by sesi200** [comment]
Relayed your message to the Motoko team

**Comment by lightninglad91** [comment]
Thank you both
