### ISSUE TITLE
styled component is not working

### ISSUE THREAD

**Issue by Sandip-2001** [dfinity/portal#489]
I have styles.js file where I have all the styles. I have imported it in my all react jsx components. but its not working.
and I have some images in assets folder. this is also not working. this is the error I am getting "Module parse failed: Unexpected character '�' (1:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file."

**Comment by sesi200** [comment]
Can you explain in a bit more detail what you are trying to do and how this relates to this repo, please?

**Comment by jessiemongeon1** [comment]
This repo has recently undergone several major updates and changes, including style changes. Closing this issue as it is most likely outdated. 

Please feel free to reopen this issue if you are still experiencing this issue with the latest version of the repo.
