### ISSUE TITLE
Discord channel #cycles-faucet is not available

### ISSUE THREAD

**Issue by ShrutiDas-95** [dfinity/portal#493]
According to the documentation I can't find the #cycles-faucet on discord.
This is what showing me .
![Capture1](https://user-images.githubusercontent.com/94116350/190074547-a43ed213-5723-4381-bd77-fb608f081f03.PNG)

**Comment by sesi200** [comment]
I suspect you are on the wrong Discord channel. The right one is called "DFINITY DEV OFFICIAL", which is the one you get to if you go to https://faucet.dfinity.org and click on "Request Cycles".

**Comment by ShrutiDas-95** [comment]
After clicking on "Request Cycles" this window has open .
![image](https://user-images.githubusercontent.com/94116350/190081655-cccf40d5-12e2-4733-abe5-ac599633a6be.png)

There has no option for "Request Cycles".Where do find the Request option ?

**Comment by sesi200** [comment]
Looks like your Discord is not loading properly. I don't see the right logo and no loaded channels. This is how it looks when it's loaded properly:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/14757975/190082381-757a5422-c297-4ee7-82a6-b41269e02591.png">
Can you try clearing your cache or opening it through a private window?
