### ISSUE TITLE
This link points to an internal link. Needs to be made public

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/portal#524]
https://github.com/dfinity/portal/blob/b7f469cc310775be7c2fe9cb19fd6c3a48419cbc/docs/references/security/general-security-best-practices.md?plain=1#L81

**Comment by sesi200** [comment]
Just 10 hours before you created this issue someone brought the topic up internally 😄 Thank you very much for pointing this out and showing some interest in security!

I'll try to keep you posted on updates to the status

**Comment by saikatdas0790** [comment]
This link as well which points to the same document

https://github.com/dfinity/portal/blob/799f1a49e42e8405b6e3c6f0fca519d1edb94f89/docs/references/security/rust-canister-development-security-best-practices.md?plain=1#L434

**Comment by jessiemongeon1** [comment]
This link is no longer included in the docs, so I am closing this issue.
