### ISSUE TITLE
Several issues when walk through the "Adding and searching simple records (Rust)" tutorial

### ISSUE THREAD

**Issue by KevynTang** [dfinity/portal#539]
Hi, I'm very new to the IC and the Rust programming language, I met some difficulties when trying to go through the **Building on the IC -> CDKs -> cdk-rs by DFINITY (Rust) -> Adding and searching simple records** tutorial. 

> On the developer doc: [Adding and searching simple records](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile/)
> On GitHub: [rust-profile.md](https://github.com/dfinity/portal/blob/master/docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile.md)

I cannot successfully run the code if I strictly follow the steps, here are some problems I detected from my very superficial understanding. 

In the `Modify the default project` section, some descriptions confused me a bit, such as:

> Open the template `src/rust_profile/lib.rs` file in a text editor and delete the existing content.
> 
> The next step is to add a Rust program that implements the `getSelf`, `update`, `get`, and `search` functions.
> 
> Copy and paste [this code](https://github.com/dfinity/portal/blob/master/docs/developer-docs/build/_attachments/profile.rs) into the `profile.rs` file.
> 
> Save your changes and close the file to continue.

The file path `src/rust_profile/lib.rs` which I believe should be `src/rust_profile_backend/src/lib.rs` if someone create the project with `dfx new --type=rust rust_profile` with the current version of `dfx`, this issue also occurs in other parts of the tutorial, such as the place talking about `Cargo.toml`. Besides, I think the file `profile.rs` was put into the tutorial without enough context and explanation, We can just write the new code into `lib.rs` or expressly mention about declaring profile module in `lib.rs` with `mod profile;`

In the refered sample code ([this code](https://github.com/dfinity/portal/blob/master/docs/developer-docs/build/_attachments/profile.rs)), there are several issues that make the code unrunnable. 
In the import statements, I believe this part:
```rust
use ic_cdk::{
    call::{self, ManualReply},
    // ...
};
```
should be:
```rust
use ic_cdk::{
    api::call::{self, ManualReply},
    // ...
};
```
I personally cannot use the original one, it always gave me an `unresolved import` error. And I also wonder why the imported `self` in this part is completely not used. 

The next problem is about the `search` function, the original code is quite strange and results in a `mismatched types` compile error. 
```rust
#[query(manual_reply = true)]
fn search(text: String) -> ManualReply<Option<Profile>> {
    let text = text.to_lowercase();
    PROFILE_STORE.with(|profile_store| {
        for (_, p) in profile_store.borrow().iter() {
            if p.name.to_lowercase().contains(&text) || p.description.to_lowercase().contains(&text)
            {
                return ManualReply::one(Some(p));
            }

            for x in p.keywords.iter() {
                if x.to_lowercase() == text {
                    return ManualReply::one(Some(p));
                }
            }
        }
    });

    ManualReply::one(None::<Profile>)
}
```
I modified it in this way to solve the problem:, should the code be like this?
```rust
#[query(manual_reply = true)]
fn search(text: String) -> ManualReply<Option<Profile>> {
    let text = text.to_lowercase();
    let mut result = ManualReply::one(None::<Profile>);
    PROFILE_STORE.with(|profile_store| {
        for (_, p) in profile_store.borrow().iter() {
            if p.name.to_lowercase().contains(&text) || p.description.to_lowercase().contains(&text)
            {
                result = ManualReply::one(Some(p));
            }

            for x in p.keywords.iter() {
                if x.to_lowercase() == text {
                    result = ManualReply::one(Some(p));
                }
            }
        }
    });
    result
}
```

In the `Call functions on the deployed canister` section, I believe all the canister name `rust_profile` should be `rust_profile_backend`. 

After all, the last obstacle I met was about `ManualReply`, I deployed and executed the code above with this testing calls:
```
dfx --identity Miles canister call rust_profile_backend update '(record {name = "Miles"; description = "Great Dane"; keywords = vec {"Boston"; "mantle"; "three-legged"}})'
# successful, return ()

dfx --identity Miles canister call rust_profile_backend search "Miles";
# error here
```
I got this error:
```
Error: Failed query call.
Caused by: Failed query call.
  The Replica returned an error: code 5, message: "IC0504: Canister rrkah-fqaaa-aaaaa-aaaaq-cai violated contract: ic0.msg_reply_data_append: the call is already replied"
```
And the way I solved this issue was not to use `ManualReply`: 
```rust
#[query]
fn search(text: String) -> Profile {
    let text = text.to_lowercase();
    let mut result: Profile = Profile { name: "".to_string(), description: "".to_string(), keywords: vec![] };
    PROFILE_STORE.with(|profile_store| {
        for (_, p) in profile_store.borrow().iter() {
            if p.name.to_lowercase().contains(&text) || p.description.to_lowercase().contains(&text)
            {
                result = p.clone();
            }

            for x in p.keywords.iter() {
                if x.to_lowercase() == text {
                    result = p.clone();
                }
            }
        }
    });
    result
}
```

In sum, all those were major problems I met when try to go through this tutorial, I hope you are so kind as to take a look on them and make this tutorial more novice-friendly. I'm also glad to participate in doc maintenance, but I think I'm still too new and need to learn more, so I decided to first open this issue.

**Comment by sesi200** [comment]
Thank you so much for all the feedback! We're trying to get a technical writer on board so that our tutorials (and all other docs as well) can stay in better shape. Your PRs are very much appreciated!

I tried to address the smaller problems in the PR above, but sadly I don't have time to do a much better job.

Minimal explanation on why the `IC0504: Canister rrkah-fqaaa-aaaaa-aaaaq-cai violated contract: ic0.msg_reply_data_append: the call is already replied` error appeared:

`ManualReply` may only be used once per call.
```
#[query(manual_reply = true)]
fn search(text: String) -> ManualReply<Option<Profile>> {
    let text = text.to_lowercase();
    let mut result = ManualReply::one(None::<Profile>);            <<<<<<<< ManualReply used once
    PROFILE_STORE.with(|profile_store| {
        for (_, p) in profile_store.borrow().iter() {
            if p.name.to_lowercase().contains(&text) || p.description.to_lowercase().contains(&text)
            {
                result = ManualReply::one(Some(p));                 <<<<<< ManualReply used a second time
            }

            for x in p.keywords.iter() {
                if x.to_lowercase() == text {
                    result = ManualReply::one(Some(p));
                }
            }
        }
    });
    result
}
```

**Comment by KevynTang** [comment]
> Thank you so much for all the feedback! We're trying to get a technical writer on board so that our tutorials (and all other docs as well) can stay in better shape. Your PRs are very much appreciated!
> 
> I tried to address the smaller problems in the PR above, but sadly I don't have time to do a much better job.
> 
> Minimal explanation on why the `IC0504: Canister rrkah-fqaaa-aaaaa-aaaaq-cai violated contract: ic0.msg_reply_data_append: the call is already replied` error appeared:
> 
> `ManualReply` may only be used once per call.
> 
> ```
> #[query(manual_reply = true)]
> fn search(text: String) -> ManualReply<Option<Profile>> {
>     let text = text.to_lowercase();
>     let mut result = ManualReply::one(None::<Profile>);            <<<<<<<< ManualReply used once
>     PROFILE_STORE.with(|profile_store| {
>         for (_, p) in profile_store.borrow().iter() {
>             if p.name.to_lowercase().contains(&text) || p.description.to_lowercase().contains(&text)
>             {
>                 result = ManualReply::one(Some(p));                 <<<<<< ManualReply used a second time
>             }
> 
>             for x in p.keywords.iter() {
>                 if x.to_lowercase() == text {
>                     result = ManualReply::one(Some(p));
>                 }
>             }
>         }
>     });
>     result
> }
> ```

Thank you for the timely help! 
For the `search` function, From your instructions I figured out an (I think) perfect version within the demo's scope in #546, the function can now run perfectly on my test environment.
