### ISSUE TITLE
FR: Publish “Release Notes” more prominently

### ISSUE THREAD

**Issue by mikhail-turilin-dfinity** [dfinity/portal#64]
## Problem
Currently, SDK Release Notes can be accessed by in 7 clicks which is hard to find:
1. Smartcontracts.org
2. Learn
3. Docs Introduction
4. Developer docs
5. Getting started
6. Introducing SDK
7. Release notes

![image](https://user-images.githubusercontent.com/103533680/163486775-961b6cfe-a67c-48bd-8e51-f06d770d5cb9.png)

Nevertheless, SDK release notes might be the best place to learn about product updates.

On the new website beta.smartcontracts.org the release notes can be accessed by 4 steps:
1. Go to beta.smartcontracts.org
2. Docs
3. Good to know
4. SDK Release Notes

![image](https://user-images.githubusercontent.com/103533680/163486919-7b388ce5-6d79-442a-bf08-dfd73ef5857e.png)

In addition, the release notes are not scrollable - the developer needs to click on each version number to access the information.

## Solution
I propose the following website and process changes:
- Move Release Notes to the top level of smartcontracts.org
- Make Release Notes scrollable
- Publish release notes on the developer forum to get community feedback 
- Publish links to each release’s notes to other social channels: Discord, Twitter, Telegram, and others

In addition, we can consider creating an “IC developer blog” that publishes other important information for developers. For example, there’s a lot of useful information in https://kyle-peacock.com/blog which could be cross-posted (if Kyle agrees) to the main IC developer blog. Maybe other developers will also be interested in contributing.

**Comment by Acetarax** [comment]
> ## Problem
> Currently, SDK Release Notes can be accessed by in 7 clicks which is hard to find:
> 
> 1. Smartcontracts.org
> 2. Learn
> 3. Docs Introduction
> 4. Developer docs
> 5. Getting started
> 6. Introducing SDK
> 7. Release notes
> 
> ![image](https://user-images.githubusercontent.com/103533680/163486775-961b6cfe-a67c-48bd-8e51-f06d770d5cb9.png)
> 
> Nevertheless, SDK release notes might be the best place to learn about product updates.
> 
> On the new website beta.smartcontracts.org the release notes can be accessed by 4 steps:
> 
> 1. Go to beta.smartcontracts.org
> 2. Docs
> 3. Good to know
> 4. SDK Release Notes
> 
> ![image](https://user-images.githubusercontent.com/103533680/163486919-7b388ce5-6d79-442a-bf08-dfd73ef5857e.png)
> 
> In addition, the release notes are not scrollable - the developer needs to click on each version number to access the information.
> 
> ## Solution
> I propose the following website and process changes:
> 
> * Move Release Notes to the top level of smartcontracts.org
> * Make Release Notes scrollable
> * Publish release notes on the developer forum to get community feedback
> * Publish links to each release’s notes to other social channels: Discord, Twitter, Telegram, and others
> 
> In addition, we can consider creating an “IC developer blog” that publishes other important information for developers. For example, there’s a lot of useful information in https://kyle-peacock.com/blog which could be cross-posted (if Kyle agrees) to the main IC developer blog. Maybe other developers will also be interested in contributing.

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by jessiemongeon1** [comment]
This issue is outdated, as Release Notes are no longer published on the Dev Docs sidebar.
