### ISSUE TITLE
Make "Hello world" walkthrough more structured

### ISSUE THREAD

**Issue by mikhail-turilin-dfinity** [dfinity/portal#65]
I find "Hello world" walkthrough navigation a bit intimidating - there's too much information there. Do we have any other ways to structure a step-by-step guide?

![CleanShot 2022-04-14 at 17 08 19@2x](https://user-images.githubusercontent.com/103533680/163495794-04d3db39-3c1b-42f5-be0a-dd200ee29ff2.png)

The gold standard here would be Stripe which has [tutorials](https://stripe.com/docs/checkout/quickstart) where the steps are linked to the code. However, it's probably hard to implement.
![CleanShot 2022-04-14 at 17 16 02@2x](https://user-images.githubusercontent.com/103533680/163496360-49234dc5-1389-46d2-947e-f9b6a4b471c6.png)

[Plaid API](https://plaid.com/docs/quickstart/#introduction) is probably closer to what we can create in a short term. It's nicely laid out, not intimidating, and easy to follow:
![CleanShot 2022-04-14 at 17 21 18@2x](https://user-images.githubusercontent.com/103533680/163496586-ebe7042a-adc0-4062-9c97-713886dcdbe8.png)

**Comment by jessiemongeon1** [comment]
Hello, World has recently been updated and simplified: https://internetcomputer.org/docs/current/developer-docs/getting-started/hello-world
