### ISSUE TITLE
why are we writing candid by hand?

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#788]
[this](https://forum.dfinity.org/t/automatic-generation-of-candid-from-rust/14627/2?u=cryptoschindler) exists, why are we writing candid by hand in the [rust tutorial](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile#update-interface-description-file)?

**Comment by domwoe** [comment]
We should add it.

**Comment by jessiemongeon1** [comment]
The linked Rust tutorial no longer exists, and we now have a docs page on generating Candid for Rust: https://internetcomputer.org/docs/current/developer-docs/backend/rust/generating-candid

Closing this issue.
