### ISSUE TITLE
rust toolchain version

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#791]
> The Rust tool chain must be at version 1.46.0, or later.

what does this mean? how do i check the version of my rust toolchain? i assume this is the `rustc` version, if so we should phrase it as such.

this sentence appears in the rust cdk tutorials, like [here](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-counter).

**Comment by sesi200** [comment]
Yes, this is the rustc version

**Comment by jessiemongeon1** [comment]
The linked tutorial no longer exists, and the docs do not currently contain this language referring to the Rust toolchain. Closing this issue.
