### ISSUE TITLE
local canister execution environment processes

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#792]
> You have stopped any local canister execution environment processes running on your computer.

the above sentence appears in any of the [rust cdk tutorials](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-counter). i think a newbie can't make any sense of it. i propose we 

a) remove this entirely, as of `dfx 0.12.0` we have a global execution environment running, and rerunning just tells us that it's already running
b) rephrase this sentence with instructions to make it more understandable

**Comment by jessiemongeon1** [comment]
This issue is being resolved in: https://github.com/dfinity/portal/pull/2633
