### ISSUE TITLE
repetitive tutorials

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#795]
rust tutorials ([hello world](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-quickstart), [simple records](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile), [counter](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-counter)) are basically the same, only difference is that you copy a different code snippet and `hello world` explains the project structure. we should either

a) make distinctive tutorials by creating the dapp step by step
b) remove redundant tutorials and just point people to the examples

**Comment by sesi200** [comment]
Since these examples also exist in dfinity/examples I think it makes sense to remove those

**Comment by jessiemongeon1** [comment]
The latter two tutorial pages no longer exist. Closing this issue.
