### ISSUE TITLE
edit `optimize rust program` section

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#796]
i digged [this](https://forum.dfinity.org/t/wasm-module-contains-a-function-that-is-too-complex/15407/18?u=cryptoschindler) up in the forum.

if it is true, we should edit/remove the entire [optimize rust section](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-optimize).

**Comment by jessiemongeon1** [comment]
The docs for optimizing Rust canisters have since been updated: https://internetcomputer.org/docs/current/developer-docs/backend/rust/optimizing/
