### ISSUE TITLE
default dfx start command

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#799]
the [record example](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile#start-the-local-execution-environment) uses `dfx start --clean --background`, other use just `dfx start --background`. 

we should decide on one of them and update tutorials accordingly

**Comment by sesi200** [comment]
Since the tutorials all create a new project I don't think it matters all that much. But having the same everywhere would make a better impression. I personally would go for `dfx start --clean --background`

**Comment by jessiemongeon1** [comment]
This issue is being resolved in: https://github.com/dfinity/portal/pull/2633
