### ISSUE TITLE
let users decide which CDK they want to use for quickstart

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#811]
currently the [top level quickstart](https://internetcomputer.org/docs/current/developer-docs/quickstart/hello10mins) lets user deploy a dapp using the motoko cdk. ideally we let people choose which language they want to use and provide links to the respective cdks.

**Comment by jessiemongeon1** [comment]
The latest Hello World quickstart example includes code for Motoko/Rust/Azle/Kybra: https://internetcomputer.org/docs/current/developer-docs/getting-started/hello-world
