### ISSUE TITLE
no asset canister documentation

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#812]
even though hosting secure frontends on the IC is a unique selling point and constantly brought up in keynotes, there is not a single entry in the docs talking about how they work and what exactly they are.

**Comment by letmejustputthishere** [comment]
- include uploading files from browser and node (present in js agent docs)
- link from quickstart guide

**Comment by jessiemongeon1** [comment]
New asset canister docs have been added: https://github.com/dfinity/portal/pull/3306
