### ISSUE TITLE
fix `local-testing.md` instruction

### ISSUE THREAD

**Issue by neeboo** [dfinity/portal#821]
When we need to add whitelist, here we have instruction as followings

```
# This command assumes that you are using an unencrypted identity and that you are using the identity you want to deploy the SNS with.
$(dfx cache show)/ic-admin --secret-key-pem ~/.config/dfx/identity/$(dfx identity whoami)/identity.pem --nns-url "https://localhost:$(dfx info replica-port)" propose-to-update-sns-deploy-whitelist --added-principals "$(dfx identity get-wallet)" --proposer "$DEVELOPER_NEURON_ID" --proposal-title "Let me SNS!" --summary "I am friendly."
```

2 problem here:
1.`ic-admin --secret-key-pem` only support pem format of ed25519, not secp256k1, because latest dfx will generate pem of secp256k1 by default. `ic-admin` should support it as well.
2. `https://localhost` should be `http://`

**Comment by sesi200** [comment]
State of problem 1 (@max-dfinity is working on it):
```
Re: secp256k1:  The core change is done but I still need to update some related code and coax CI into a happy state
```
until then, keys can be generated with `openssl ecparam -name secp256k1 -genkey -out identity.pem`

**Comment by jessiemongeon1** [comment]
secp256k1 has been implemented. Closing this issue
