### ISSUE TITLE
documentation around testing

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/portal#861]
there are no best practices/docs around testing motoko code. this should be added.

**Comment by sesi200** [comment]
There's a few things on @krpeacock's blog about testing, but I don't know the current state of the art.
- https://kyle-peacock.com/blog/motoko/unit-testing
- https://kyle-peacock.com/blog/dfinity/simple-canister-e2e

**Comment by letmejustputthishere** [comment]
https://forum.dfinity.org/t/what-are-the-best-tools-to-test-canisters-written-in-motoko-what-i-ve-tried-so-far-is-surprisingly-big-of-a-pain/16474?u=cryptoschindler
