### ISSUE TITLE
network deploy refers to wrong cansister

### ISSUE THREAD

**Issue by testpuddle** [dfinity/portal#876]
This line of code:
dfx canister --network ic call hello greet '("everyone": text)'
// Error: Failed to determine id for canister 'hello'.

should be:
dfx canister --network ic call hello_backend greet '("everyone": text)'
// ("Hello, everyone!")

**Comment by sesi200** [comment]
Thanks for reporting this! Would you mind showing me on which page that is?

**Comment by testpuddle** [comment]
Oops!  That would help.  

https://internetcomputer.org/docs/current/developer-docs/quickstart/network-quickstart

Here is the section
4.  Call the hello canister and the predefined greet function by running the following command:

dfx canister --network ic call hello **greet** '("everyone": text)'
