### ISSUE TITLE
Example is build for dfx 0.6.22 

### ISSUE THREAD

**Issue by testpuddle** [dfinity/portal#911]
Any chance in updating the example git for the linkedup sample to a  more recent dfx version and node build?

**Comment by sesi200** [comment]
I don't think we can find the time to do all of that. But if you have any specific problems you run into I'm happy to help you

**Comment by jessiemongeon1** [comment]
There are no plans to update the LinkedUp sample at this time. Closing this issue; will reopen if this sample is updated in the future.
