### ISSUE TITLE
The ledger / token tutorial does not mention ICRC-1 and does not contain the interface in the .did

### ISSUE THREAD

**Issue by ocluf** [dfinity/portal#982]
If you currently follow the ledger tutorial you will get a ledger that does not implement ICRC-1 except if you take the effort to follow the link and, get the latest blessed commit, and change the command. 

I expect most people would be to lazy initially to click and find the latest blessed replica commit, but even if you did the ledger.did does not contain the ICRC-1 interfaces even though you can call them. This causes the interface to also not show up if you open the canister in CandidUI. 

To drive adoption of ICRC-1 it would probably be best to update the .did, the tutorial commit hash, and to link to the ICRC-1 specification in the tutorial.

**Comment by sesi200** [comment]
@letmejustputthishere you did a lot of QoL changes to the docs. Would you mind taking this one on as well?

**Comment by jessiemongeon1** [comment]
Documentation for the ICRC-1 ledger and tokens now exists:

https://internetcomputer.org/docs/current/developer-docs/defi/icrc-1/icrc1-ledger-setup
https://internetcomputer.org/docs/current/developer-docs/defi/icrc-1/using-icrc1-ledger
