### ISSUE TITLE
document translation (kr)

### ISSUE THREAD

**Issue by minkj1992** [dfinity/portal#998]
Hi, I am a developer living in Korea.
Recently, I began to take an interest to the Internet computer ecosystem, and I've been reading the documents of the portal.

While reading the documents, I want to translate them into Korean, but the policy for translation is not written in the contribution on `readme.md`, so I ask it in here.

Is there anyone who can help with this?

**Comment by sesi200** [comment]
Hi Jaedal, thank you very much for your offer! I asked the team if 1) we have a mechanism to support a multi-language website and 2) if we are interested in having the docs available for multiple languages. I'll update you if I hear back from them.

**Comment by minkj1992** [comment]
Thank you for reply fast @sesi200. I want to support difinty's vision and there are a lot of excellent developers in korea. 

I wish many korean developers contribute ICP's "distribution".

**Comment by sesi200** [comment]
Glad to see you're so enthusiastic! If you want to do something before I have any more news, you could always start to write your own tutorials/explanations in Korean and put them on a blog. If you have a personal one, that would be great, otherwise maybe through [papy.rs](https://papy.rs/)

**Comment by minkj1992** [comment]
Thank you. I've not known about papy, I'll try it tomorrow (GMT+9). Kudos for ICP I think it is really great project.

**Comment by jessiemongeon1** [comment]
@minkj1992 Our AI bot (a recent addition to the docs) has been useful for some language translations. I'd recommend you try that out to see if it helps.
