### ISSUE TITLE
Link Staking Interest Calculator

### ISSUE THREAD

**Issue by miaadriaens** [dfinity/portal#999]
Adding a link to the Staking Interest Calculator on https://www.stakingrewards.com/earn/dfinity/. Super valuable resource for your community and will lead to increased staking participation.

**Comment by sesi200** [comment]
Thank you very much for the suggestion, @miaadriaens! I had a look at the calculator, and unfortunately I have to say it is misleading at best, and maybe even outright wrong in many cases.

For example, currently, if you stake for less than 180 days, you won't get any rewards. The calculator, however, says that even a 7 day staking period gives rewards. Also, for longer lockup periods (e.g. 10 years) the extra rewards you get are way too low.

If you have a (somewhat) correct calculator you'd like to have linked along with a suggestion where to link to it, feel free to reopen this issue.
